apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dev-psql-cluster
  namespace: dev
spec:
  teamId: "dev"
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    db_owner:
    - superuser
    - createdb
  preparedDatabases:
    hasura:
      defaultUsers: true
  postgresql:
    version: "13"
