apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
spec:
  releaseName: mongodb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 10.3.4
  auth:
    rootPassword: test1234