apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mongodb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami
    version: 4.4.3
  values:
    architecture: standalone