apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~5.0
    fluxcd.io/locked: "true"
    fluxcd.io/locked_msg: "Halt updates for now"
    fluxcd.io/locked_user: "Stefan Prodan <stefan@weave.works>"
spec:
  releaseName: mongodb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: bitnami
    version: 10.3.4
  values:
    architecture: standalone