apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: psql-operator
  namespace: psql
spec:
  releaseName: psql-operator
  chart:
    git: git@github.com:zalando/postgres-operator
    ref: master
    path: charts/postgres-operator