apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: pgo
spec:
  releaseName: postgres-operator
  chart:
    git: git@github.com:zalando/postgres-operator
    ref: master
    path: charts/postgres-operator